export const selectors = {
  catalogProducts: '.products',
  shoesTemplate:'.shoes-card-template',
  shoesCardImage:'.shoes-card__image',
  shoesCardName:'.shoes-card__name',
  shoesCardCategory:'.shoes-card__category',
  shoesCardBrand:'.shoes-card__brand',
  shoesCardMaterial:'.shoes-card__material',
  shoesCardPrice:'.shoes-card__price',
  shoesCardColor:'.shoes-card__colors',
  shoesCardStock:'.basket__stock',
  shoesCardBasketButton:'.basket__stock-button',
  modalWindow:'.modal-window-overlay',
  popupButton:'.popup__button',
  searchField:'#input-search',
  categoryListName:'#checkbox__category',
  checkboxList:'.custom-checkbox',
  priceSlider:'.slider',
  colorListName: '.colors',
  colorList: '.checkbox-color',
  sizeListName: '.sizes',
  sizeList:'.checkbox-size',
  brandListName: '#brands',
  option: 'option',
  materialListName: '.material__radio-buttons',
  radioButton:'.custom-radio',
  cleanFiltersButton:'.clear-button',
  sliderPointRight:'slider-1',
  sliderPointLeft:'slider-2',
  sliderValueRight:'range1',
  sliderValueLeft:'range2',
  sliderTrack:'.slider-track',
  selectedColor: 'color__active',
  selectedSize: 'size__active',
};
