import { ICards } from '../models/inrefaces'

export const cards: ICards[] = [
  {
    name: 'Nike Waffle One SE',
    category: 'Basketball',
    price: '89',
    gender: 'Mens Shoes',
    color: 'black',
    size: '4.5',
    brand: 'Nike By You',
    material: 'Canvas',
    img: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/29082110-583d-4021-9ff0-57d2cff36c9b/waffle-one-se-shoes-mT3CQN.png',
    release: '2021',
    stock: true
  },
  {
    name: 'Nike Air Force 1',
    category: 'Running',
    price: '115',
    gender: 'Mens Shoes',
    color: 'red',
    size: '7.5',
    brand: 'Jordan',
    material: 'Leather',
    img:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/05aeb54f-ca86-48d9-a60f-57d798e3935d/air-max-95-shoes-TJLLsB.png',
    release: '2021',
    stock: true
  },
  {
    name: 'Nike Air Force 2',
    category: 'Jordan',
    price: '100',
    gender: 'Mens Shoes',
    color:'white',
    size: '5.0', 
    brand: 'Nike Sportwear',
    material: 'Leather',
    img:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/358b5ffe-0704-4c5a-89fd-0fa5b2b1f99b/air-max-plus-iii-shoe-3BSBtx.png',
    release: '2020',
    stock: true
  },
  {
    name: 'Nike Air Force 3',
    category: 'Lifestyle',
    price: '198',
    gender: 'Mens Shoes',
    color: 'red',
    size: '4.0',
    brand: 'NikeLab',
    material: 'Sustainable Materials',
    img:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/312e0df6-a0c6-4a5d-ba01-e837b3d8ee49/jordan-delta-3-sp-shoes.png',
    release: '2019',
    stock: false
  },
  {
    name: 'Nike Air Force 4',
    category: 'Football',
    price: '156',
    gender: 'Mens Shoes',
    color: 'pink',
    size: '6.0',
    brand: 'Jordan',
    material: 'Sustainable Materials',
    img: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4180e725-4966-463b-8c22-71e3ca6a9a55/air-jordan-2-retro-sp-shoes.png',
    release: '2022',
    stock: false
  },
  {
    name: 'Nike Air Force 5',
    category: 'Training',
    price: '178',
    gender: 'Mens Shoes',
    color:  'green',
    size: '5.5',
    brand: 'Nike By You',
    material: 'Sustainable Materials',
    img: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/0db30447-d199-4373-bf36-6cbb439e96c2/air-max-terrascape-90-shoes-wdBkKH.png',
    release: '2020',
    stock: false
  },
  {
    name: 'Nike Air Force 6',
    category: 'Skateboarding',
    price: '260',
    gender: 'Mens Shoes',
    color: 'green',
    size: '3.5',
    brand: 'ACG',
    material: 'Sustainable Materials',
    img: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e6b5dd64-1a32-45f8-8f19-8f421a1cdd6d/air-max-terrascape-90-shoes-CRn0XW.png',
    release: '2021',
    stock: true
  },
  {
    name: 'Nike Air Force 7',
    category: 'Golf',
    price: '240',
    gender: 'Mens Shoes',
    color: 'red',  
    size: '3.0',
    brand: 'NikeLab',
    material: 'Canvas',
    img: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/271371f3-0f5c-47c7-b4b4-f840e8b488c1/air-pegasus-83-shoes-hq200x.png',
    release: '2020',
    stock: false
  },
  {
    name: 'Nike Air Force 8',
    category: 'Tennis',
    price: '222',
    gender: 'Mens Shoes',
    color: 'blue',
    size: '8.0',
    brand: 'ACG',
    material: 'Canvas',
    img: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/b00a5170-20ed-4cda-9c69-6c1e0a04276e/air-force-1-07-shoes-KprQCr.png',
    release: '2022',
    stock: false
  },
  {
    name: 'Nike Waffle One SE',
    category: 'Basketball',
    price: '89',
    gender: 'Mens Shoes',
    color: 'black',
    size: '4.5',
    brand: 'Nike By You',
    material: 'Canvas',
    img: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/29082110-583d-4021-9ff0-57d2cff36c9b/waffle-one-se-shoes-mT3CQN.png',
    release: '2021',
    stock: true
  },
  {
    name: 'Nike Air Force 1 07 LV8',
    category: 'Running',
    price: '139',
    gender: 'Mens Shoes',
    color: 'red',
    size: '4.5',
    brand: 'Jordan',
    material: 'Leather',
    img:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d175869d-a0df-486c-b546-f59aa710c77c/air-force-1-07-lv8-shoes-KkS3Cf.png',
    release: '2022',
    stock: true
  },
  {
    name: 'Nike x Stüssy Air Force 1 07 Mid',
    category: 'Jordan',
    price: '111',
    gender: 'Mens Shoes',
    color:'white',
    size: '8.5', 
    brand: 'Nike Sportwear',
    material: 'Leather',
    img:'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/9f810fa0-25ea-4880-89d0-e6f1e124aa02/stussy-air-force-1-07-mid-shoes-bdsfmH.png',
    release: '2020',
    stock: true
  },
  {
    name: 'Nike Air Max 97',
    category: 'Lifestyle',
    price: '167',
    gender: 'Mens Shoes',
    color: 'red',
    size: '3.5',
    brand: 'NikeLab',
    material: 'Sustainable Materials',
    img:'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/c7fa66ed-271a-4f37-9425-d83a5ed742ae/air-max-97-shoes-9QwZMc.png',
    release: '2019',
    stock: false
  },
  {
    name: 'Air Jordan 1 Retro High OG',
    category: 'Football',
    price: '103',
    gender: 'Mens Shoes',
    color: 'pink',
    size: '6.0',
    brand: 'Jordan',
    material: 'Sustainable Materials',
    img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/e5841dd7-c5c6-444f-afdf-89e3b87ceceb/air-jordan-1-retro-high-og-shoes-79vGWV.png',
    release: '2022',
    stock: false
  },
  {
    name: 'Nike Air Max 95 Essential',
    category: 'Training',
    price: '154',
    gender: 'Mens Shoes',
    color:  'green',
    size: '6.5',
    brand: 'Nike By You',
    material: 'Sustainable Materials',
    img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/c5bf1010-00cf-4461-81b4-16efc6abbdef/air-max-95-essential-shoes-Zgg3pn.png',
    release: '2020',
    stock: false
  },
  {
    name: 'Nike x ACRONYM® Blazer Low',
    category: 'Skateboarding',
    price: '299',
    gender: 'Mens Shoes',
    color: 'green',
    size: '7.0',
    brand: 'ACG',
    material: 'Sustainable Materials',
    img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/d8ac9255-b966-443b-9934-edc835b59d19/acronym-blazer-low-shoes-H6l3kD.png',
    release: '2021',
    stock: true
  },
  {
    name: 'Nike Air Max Plus',
    category: 'Golf',
    price: '201',
    gender: 'Mens Shoes',
    color: 'red',  
    size: '8.0',
    brand: 'NikeLab',
    material: 'Canvas',
    img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/8109efda-cdb6-4d19-9fa1-b970dbb653a6/air-max-plus-shoes-x37n30.png',
    release: '2020',
    stock: true
  },
  {
    name: 'Nike Pegasus Trail 3 GORE-TEX',
    category: 'Tennis',
    price: '267',
    gender: 'Mens Shoes',
    color: 'blue',
    size: '3.0',
    brand: 'ACG',
    material: 'Canvas',
    img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/216ba0e1-8875-488c-8576-d76cde6a291c/pegasus-trail-3-gore-tex-waterproof-trail-running-shoes-FngTl6.png',
    release: '2022',
    stock: true
  },
  {
    name: 'KD15',
    category: 'Jordan',
    price: '111',
    gender: 'Mens Shoes',
    color:'white',
    size: '5.5', 
    brand: 'Nike Sportwear',
    material: 'Leather',
    img:'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/54cf8fb6-5eb3-4147-aa44-4a11cc2668f4/kd15-basketball-shoes-0H8pmQ.png',
    release: '2020',
    stock: true
  },
  {
    name: 'Nike Zoom Alphafly Next Nature',
    category: 'Lifestyle',
    price: '167',
    gender: 'Mens Shoes',
    color: 'red',
    size: '6.5',
    brand: 'NikeLab',
    material: 'Sustainable Materials',
    img:'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/04993055-6221-4a74-8ff2-bd37b481c057/zoom-alphafly-next-nature-road-racing-shoe-3mk9g2.png',
    release: '2019',
    stock: false
  },
  {
    name: 'Air Jordan 1 Retro High OG',
    category: 'Football',
    price: '103',
    gender: 'Mens Shoes',
    color: 'pink',
    size: '6.0',
    brand: 'Jordan',
    material: 'Sustainable Materials',
    img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/e5841dd7-c5c6-444f-afdf-89e3b87ceceb/air-jordan-1-retro-high-og-shoes-79vGWV.png',
    release: '2022',
    stock: false
  },
  {
    name: 'NikeCourt Zoom Pro',
    category: 'Training',
    price: '154',
    gender: 'Mens Shoes',
    color:  'green',
    size: '6.5',
    brand: 'Nike By You',
    material: 'Sustainable Materials',
    img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/42a6a00e-11d9-4bfd-beea-688c53affed7/nikecourt-zoom-pro-clay-court-tennis-shoes-qJFxc8.png',
    release: '2020',
    stock: false
  },
  {
    name: 'Nike x ACRONYM® Blazer Low',
    category: 'Skateboarding',
    price: '299',
    gender: 'Mens Shoes',
    color: 'green',
    size: '7.0',
    brand: 'ACG',
    material: 'Sustainable Materials',
    img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/d8ac9255-b966-443b-9934-edc835b59d19/acronym-blazer-low-shoes-H6l3kD.png',
    release: '2021',
    stock: true
  },
  {
    name: 'Air Jordan 1 Low FlyEase',
    category: 'Golf',
    price: '201',
    gender: 'Mens Shoes',
    color: 'red',  
    size: '8.0',
    brand: 'NikeLab',
    material: 'Canvas',
    img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/368aab4d-4493-4d23-b8df-5e41bfbaf89e/air-jordan-1-low-flyease-easy-on-off-shoes-8HnsGF.png',
    release: '2020',
    stock: true
  },
  {
    name: 'Nike Air Zoom Tempo NEXT%',
    category: 'Tennis',
    price: '267',
    gender: 'Mens Shoes',
    color: 'blue',
    size: '8.5',
    brand: 'ACG',
    material: 'Canvas',
    img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/b69d1007-7a39-46bd-8236-42a002dc8326/air-zoom-tempo-next-road-running-shoes-7kzrjk.png',
    release: '2022',
    stock: true
  }
]